In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sanyamdhadiwal2302/netflix-data/mymoviedb.csv

In [2]:
import pandas as pd
import os
os.listdir()
df = pd.read_csv(
    '/kaggle/input/datasets/sanyamdhadiwal2302/netflix-data/mymoviedb.csv',
    engine='python'
)

df.head(1)

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...

In [3]:
df.isnull()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
9832,False,False,False,False,False,False,False,False,False
9833,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False
9835,False,False,False,False,False,False,False,False,False
9836,False,False,False,False,False,False,False,False,False

In [4]:
df.isnull().sum()

Release_Date          0
Title                 9
Overview              9
Popularity           10
Vote_Count           10
Vote_Average         10
Original_Language    10
Genre                11
Poster_Url           11
dtype: int64

In [5]:
df.isnull().sum(axis=1)

0       0
1       0
2       0
3       0
4       0
       ..
9832    0
9833    0
9834    0
9835    0
9836    0
Length: 9837, dtype: int64

In [6]:
df.isnull().sum(axis=0)

Release_Date          0
Title                 9
Overview              9
Popularity           10
Vote_Count           10
Vote_Average         10
Original_Language    10
Genre                11
Poster_Url           11
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9826 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9826 non-null   object
 1   Title              9826 non-null   object
 2   Overview           9826 non-null   object
 3   Popularity         9826 non-null   float64
 4   Vote_Count         9826 non-null   object
 5   Vote_Average       9826 non-null   object
 6   Original_Language  9826 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: float64(1), object(8)
memory usage: 767.7+ KB

In [9]:
df.reset_index(drop=True, inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9826 entries, 0 to 9825
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9826 non-null   object
 1   Title              9826 non-null   object
 2   Overview           9826 non-null   object
 3   Popularity         9826 non-null   float64
 4   Vote_Count         9826 non-null   object
 5   Vote_Average       9826 non-null   object
 6   Original_Language  9826 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: float64(1), object(8)
memory usage: 691.0+ KB

In [11]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9821    False
9822    False
9823    False
9824    False
9825    False
Length: 9826, dtype: bool

In [12]:
df['Vote_Count'] = df['Vote_Count'].astype('float64')
df['Vote_Average'] = df['Vote_Average'].astype('float64')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9826 entries, 0 to 9825
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9826 non-null   object
 1   Title              9826 non-null   object
 2   Overview           9826 non-null   object
 3   Popularity         9826 non-null   float64
 4   Vote_Count         9826 non-null   float64
 5   Vote_Average       9826 non-null   float64
 6   Original_Language  9826 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: float64(3), object(6)
memory usage: 691.0+ KB

In [14]:
df.describe()

        Popularity    Vote_Count  Vote_Average
count  9826.000000   9826.000000   9826.000000
mean     40.323951   1392.943721      6.439467
std     108.879332   2611.303856      1.129797
min      13.354000      0.000000      0.000000
25%      16.128250    146.000000      5.900000
50%      21.195000    444.000000      6.500000
75%      35.179250   1376.000000      7.100000
max    5083.954000  31077.000000     10.000000

In [15]:
df.sort_values(by='Vote_Average', ascending=False).head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
9390,2020-04-09,Kung Fu Master Huo Yuanjia,The young and vigorous Huo Yuanjia was only fo...,13.745,1.0,10.0,zh,"Action, Drama",https://image.tmdb.org/t/p/original/boXAHksMko...
7338,2018-06-08,Franco Escamilla: Por La Anécdota,Mexican stand-up comedian Franco Escamilla dra...,16.158,92.0,9.2,es,Comedy,https://image.tmdb.org/t/p/original/f4iwq1hkcA...
667,2019-03-29,Demon Slayer: Kimetsu no Yaiba Sibling's Bond,Tanjiro finds his family slaughtered and the l...,86.689,27.0,9.1,ja,"Action, Animation, Fantasy",https://image.tmdb.org/t/p/original/99cJLZkNoI...
2324,2021-06-17,Impossible Things,A widow who is tormented by the memory of her ...,36.466,82.0,9.1,es,"Family, Drama",https://image.tmdb.org/t/p/original/eaf7GQj0ie...
7400,2020-10-30,My Sex Doll,The story of chaos both body and mind occurs w...,16.088,4.0,9.0,th,"Comedy, Romance",https://image.tmdb.org/t/p/original/cyVyrXq5dR...

In [16]:
df.sort_values(by='Vote_Average', ascending=True).head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
917,2022-10-07,Spider-Man: Across the Spider-Verse (Part One),Miles Morales returns for the next chapter of ...,69.174,0.0,0.0,en,"Animation, Action, Science Fiction, Comedy, Ad...",https://image.tmdb.org/t/p/original/l2hjrByNNo...
9133,2023-05-24,The Little Mermaid,A young mermaid makes a deal with a sea witch:...,14.016,0.0,0.0,en,"Adventure, Family, Fantasy, Romance",https://image.tmdb.org/t/p/original/57bEiV6qwc...
4852,2018-06-07,Nice Sister-In-Law 3,Jung-tae has become a successful businessman. ...,21.352,0.0,0.0,ko,Romance,https://image.tmdb.org/t/p/original/nW3ZaX4dOk...
8467,2022-08-24,Puss in Boots: The Last Wish,Puss in Boots discovers that his passion for a...,14.687,0.0,0.0,en,"Animation, Adventure, Comedy, Family",https://image.tmdb.org/t/p/original/2PaMTHdbF6...
1212,2022-03-16,Ambulance,"Decorated veteran Will Sharp, desperate for mo...",57.956,0.0,0.0,en,"Action, Crime, Thriller",https://image.tmdb.org/t/p/original/zT5ynZ0UR6...

In [17]:
df.sort_values(by='Popularity', ascending=False).head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940.0,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151.0,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122.0,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076.0,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793.0,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [18]:
df.sort_values(by='Popularity', ascending=True).head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
9825,1984-09-23,Threads,Documentary style account of a nuclear holocau...,13.354,186.0,7.8,en,"War, Drama, Science Fiction",https://image.tmdb.org/t/p/original/lBhU4U9Eeh...
9824,2021-03-31,The United States vs. Billie Holiday,Billie Holiday spent much of her career being ...,13.354,152.0,6.7,en,"Music, Drama, History",https://image.tmdb.org/t/p/original/vEzkxuE2sJ...
9823,2016-05-06,The Offering,When young and successful reporter Jamie finds...,13.355,94.0,5.0,en,"Mystery, Thriller, Horror",https://image.tmdb.org/t/p/original/h4uMM1wOhz...
9822,2020-10-01,Violent Delights,A female vampire falls in love with a man she ...,13.356,8.0,3.5,es,Horror,https://image.tmdb.org/t/p/original/4b6HY7rud6...
9820,1974-11-06,The Little Prince,"Based on the story by Antoine deSaint-Exupery,...",13.357,89.0,6.6,en,"Science Fiction, Fantasy, Family, Music",https://image.tmdb.org/t/p/original/ts0TGlxlBf...

In [19]:
df.sort_values(by='Vote_Count', ascending=False).head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
380,2010-07-15,Inception,"Cobb, a skilled thief who commits corporate es...",127.131,31077.0,8.4,en,"Action, Science Fiction, Adventure",https://image.tmdb.org/t/p/original/edv5CZvWj0...
461,2014-11-05,Interstellar,The adventures of a group of explorers who mak...,110.531,27975.0,8.4,en,"Adventure, Drama, Science Fiction",https://image.tmdb.org/t/p/original/gEU2QniE6E...
221,2008-07-14,The Dark Knight,Batman raises the stakes in his war on crime. ...,173.923,26994.0,8.5,en,"Drama, Action, Crime, Thriller",https://image.tmdb.org/t/p/original/qJ2tW6WMUD...
138,2012-04-25,The Avengers,When an unexpected enemy emerges and threatens...,229.772,26490.0,7.7,en,"Science Fiction, Action, Adventure",https://image.tmdb.org/t/p/original/RYMX2wcKCB...
195,2016-02-09,Deadpool,Deadpool tells the origin story of former Spec...,189.206,26390.0,7.6,en,"Action, Adventure, Comedy",https://image.tmdb.org/t/p/original/3E53WEZJqP...

In [20]:
df.sort_values(by='Vote_Count', ascending=True).head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
6484,2023-02-15,The Marvels,The sequel to Captain Marvel (2019).,17.592,0.0,0.0,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/bnz17wOkp9...
6938,2021-07-13,Deadpool and Korg React,Two members of the MCYouTube react to the upco...,16.806,0.0,0.0,en,Comedy,https://image.tmdb.org/t/p/original/qUzVrmvMyk...
6437,2022-03-25,Infinite Storm,One woman's journey for self-discovery and tur...,17.676,0.0,0.0,en,Drama,https://image.tmdb.org/t/p/original/sX51ugLCPx...
6422,2022-03-10,Madu Murni,Plot unknown.,17.697,0.0,0.0,id,"Comedy, Drama",https://image.tmdb.org/t/p/original/pwhSK1Kn0g...
6951,2022-03-11,Offseason,Upon receiving a mysterious letter that her mo...,16.783,0.0,0.0,en,"Horror, Mystery",https://image.tmdb.org/t/p/original/q7Ar9V7qh4...

In [21]:
df.to_csv("Netflix_data_cleaning.csv", index=False)

In [22]:
df.to_csv("file.csv", index=False)

In [23]:
df.to_excel("Netflix_data_cleaning.xlsx", index=False)